version: '3.7'
services:
  ## ADMIN ##
  admin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql_db
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    networks:
      - database

  ## MYSQL ##
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.29
    volumes:
      - ./database/data/dev:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: social_network
    networks:
      - database
    restart: always

  ## SERVER ##
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - mysql_db
    environment:
      - SECRET='¯\_(ツ)_/¯'
    restart: always
    command: ['./wait-for-it.sh', 'mysql_db:5432', '--', 'node', 'main.js']
    
    env_file:
      - ./server/.production.env
  ## CLIENT ##
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 3000:80
    restart: always
    env_file:
      - ./client/.env
networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
